# -*- coding: utf-8 -*-
"""github project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k0Rvnoh0Ibqd-P2lgg_4JlBe0CkA_MAS

#Task 1
"""

import requests
import pandas as pd

URL = "https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"

Response = requests.get(URL)

Response.status_code

data = Response.json()

data["items"]

Machine_Learning = pd.DataFrame(data["items"])

print("The first 5 rows of data :")
Machine_Learning.head()

print("Data columns :")
Machine_Learning.columns

print("Data types :")
Machine_Learning.dtypes

Machine_Learning.info()

print("Data shape  :")
Machine_Learning.shape

Machine_Learning = Machine_Learning[
    ['name',
     'owner' ,
     'language' ,
     'stargazers_count' ,
     'forks_count' ,
     'watchers_count' ,
     'open_issues_count' ,
     'created_at' ,
     'updated_at' ,
     'license']
]
print("Required columns selected successfully")

Machine_Learning.columns

print("The first 5 rows of data :")
Machine_Learning.head()

### Used AI assistance to understand how to extract values from nested data
# i dont find it in the content

Machine_Learning["license"] = Machine_Learning["license"].apply(
    lambda x: x["name"] if isinstance(x, dict) else x
)

Machine_Learning["owner"] = Machine_Learning["owner"].apply(
    lambda x: x["login"] if isinstance(x, dict) else x
)

print("owners:")
print(Machine_Learning['owner'])

print("\nlicense:")
print(Machine_Learning['license'])

print("missing values :")
Machine_Learning.isnull().sum()

Machine_Learning['language']= Machine_Learning['language'].fillna('Unknown')

Machine_Learning['license']= Machine_Learning['license'].fillna('Unknown')

print("missing values after cleaning :")
Machine_Learning.isnull().sum()

print("Duplicated records:")
print(Machine_Learning.duplicated().sum())   # # No duplicates to clean

Machine_Learning["created_at"] = pd.to_datetime(Machine_Learning["created_at"])
Machine_Learning["updated_at"] = pd.to_datetime(Machine_Learning["updated_at"])

Machine_Learning.info()

Machine_Learning.rename(columns={         # i searched for "rename" function
    "stargazers_count": "stars",
    "forks_count": "forks",
    "watchers_count": "watchers",
    "open_issues_count": "open_issues",
    "created_at": "created_date",
    "updated_at": "updated_date"
}, inplace=True)

print("Data columns  after cleaning :")
Machine_Learning.columns     # check the columns

Machine_Learning.to_csv("github_projects.csv", index=False)

github_projects = pd.read_csv("github_projects.csv")

print ("The first 5 raws of data :")
github_projects.head()

print("\nData columns :")
github_projects.columns

print("\nData types :")
github_projects.dtypes

github_projects.info()

print("\nData shape  :")
github_projects.shape

"""#Task 2"""

# Commented out IPython magic to ensure Python compatibility.
!pip install ipython-sql==0.5.0 prettytable==3.9.0
# %load_ext sql
# %config SqlMagic.style = 'PLAIN_COLUMNS'
# %sql sqlite:///github_projects.db
import sqlite3 as sql

github_projects = pd.read_csv("github_projects.csv")

conn = sql.connect("github_projects.db")

github_projects.to_sql( "Repositories",
conn,if_exists="replace",index=False)

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories
# WHERE stars > 10000;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT*
# FROM Repositories
# WHERE name LIKE '%Machine%';

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories
# WHERE language = "Python"
# OR language = "Unknown" ;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories
# WHERE stars > 7000
# AND NOT license = 'MIT License';

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories
# WHERE language = "Python"
# AND license = "Unknown" ;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories
# ORDER BY stars DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories
# ORDER BY stars ASC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM Repositories
# ORDER BY stars DESC
# LIMIT 10;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT COUNT(*) AS Total_Repositories
# FROM Repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT AVG(stars) AS Average_stars
# FROM Repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT language
# FROM Repositories
# GROUP BY  language;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT language,COUNT(*) AS Repositories
# FROM Repositories
# GROUP BY  language
# HAVING COUNT(*)> 5 ;

import matplotlib.pyplot as plt
top_repositories = github_projects.sort_values('stars', ascending=False).head(5)

plt.figure(figsize=(10, 6))
plt.title('Top 5 Repositories by Stars')
plt.bar(top_repositories ['name'],top_repositories ['stars'])
plt.xlabel('Repository')
plt.ylabel('Stars')
plt.show()

github_projects["created_date"] = pd.to_datetime(github_projects["created_date"])
creation_trend = github_projects["created_date"].dt.year.value_counts().sort_index()
plt.figure(figsize=(8,5))
plt.plot(creation_trend.index, creation_trend.values, marker="o")
plt.title("Repository Creation Trends Over Time")
plt.xlabel("Year")
plt.ylabel("Number of Repositories")
plt.show()

"""# Step 8: Interpretation of Results

- The dataset contains 100 GitHub repositories related to Machine Learning

- TensorFlow is the most popular repository


- 2018 was the year with the highest number of repository creations

- Python is the most commonly used programming language

- There are 23 repositories with an unknown programming language
"""